export const MOCK_ADD_TO_CART = 'MOCK_ADD_TO_CART';
export const MOCK_REMOVE_FROM_CART = 'MOCK_REMOVE_FROM_CART';
export const MOCK_ADJUST_QTY = 'MOCK_ADJUST_QTY';
export const MOCK_TOGGLE_CART = 'MOCK_TOGGLE_CART';
export const MOCK_TOGGLE_CURRENCY = 'MOCK_TOGGLE_CURRENCY';
export const MOCK_SELECT_CURRENCY = 'MOCK_SELECT_CURRENCY';

// UPDATE ATTRIBUTES IN CART
export const MOCK_UPDATE_ATTRIBUTES_IN_CART = 'MOCK_UPDATE_ATTRIBUTES_IN_CART';

// FULL DATA CATEGORIES + PRODUCTS
export const MOCK_SET_CATEGORIES_AND_PRODUCTS = 'MOCK_SET_CATEGORIES_AND_PRODUCTS';

// CURRENCIES
export const MOCK_SET_CURRENCIES = 'MOCK_SET_CURRENCIES';
