export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADJUST_QTY = 'ADJUST_QTY';
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM';
export const TOGGLE_CART = 'TOGGLE_CART';
export const TOGGLE_CURRENCY = 'TOGGLE_CURRENCY';
export const SELECT_CURRENCY = 'SELECT_CURRENCY';

// FULL DATA CATEGORIES + PRODUCTS
export const SET_CATEGORIES_AND_PRODUCTS = 'SET_CATEGORIES_AND_PRODUCTS';

// CURRENCIES
export const SET_CURRENCIES = 'SET_CURRENCIES';
